true  = True
false = False

campaign = {
  "id":                                1032,
  "name":                              "",
  "active":                            false,
  "dialStatusA":                       "",
  "leadOrder":                         "DOWN",
  "parkExt":                           "",
  "parkFileName":                      "",
  "webFormAddress":                    "/osdial/agent/webform_redirect.php",
  "allowClosers":                      true,
  "hopper_level":                      200,
  "autoDialLevel":                     "5",
  "nextAgentCall":                     "oldest_call_finish",
  "localCallTime":                     "15",
  "voiceMailExtension":                "",
  "dialTimeout":                       30,
  "dialPrefix":                        "9",
  "cid":                               "",
  "vdadExtension":                     "",
  "recordingExtension":                "",
  "recording":                         "ALLCALLS",
  "recordingFileName":                 "ALLCALLS",
  "script":                            "",
  "getCallLaunch":                     "NONE",
  "amdSendToVmx":                      "N",
  "xferConfANumber":                   "CXFER",
  "xferConfBNumber":                   "AXFER",
  "altNumberDialing":                  false,
  "allowScheduledCallBacks":           true,
  "dropCallSeconds":                   5,
  "allowSafeHarborMessage":            true,
  "allowSafeHarborExtension":          false,
  "allowDisplayDialableCount":         true,
  "wrapUpSeconds":                     0,
  "wrapUpMessage":                     "Wrapup Call",
  "allowUseInternalDnc":               false,
  "allCallsDelay":                     0,
  "omitPhoneCode":                     true,
  "dialMethod":                        "RATIO",
  "availableOnlyRatioTally":           true,
  "adaptiveDroppedPercentage":         3,
  "adaptiveMaximumLevel":              "3.0",
  "adaptiveLatestServerTime":          "2100",
  "adaptiveIntensity":                 "0",
  "adaptiveDlDiffTarget":              0,
  "concurrentTransfers":               "AUTO",
  "autoAltDial":                       "NONE",
  "AutoAltDialStatuses":               "AUTODIAL STATUS LIST",
  "agentPauseCodesActive":             false,
  "description":                       "",
  "changeDateTime":                    "",
  "statsRefresh":                      false,
  "dialStatuses":                      "STATUS LIST",
  "disableAlterCustData":              false,
  "noHopperLeadsLogins":               true,
  "listOrderMix":                      "DISABLED",
  "allowCampaignInbound":              true,
  "manualDialListId":                  999,
  "defaultXferGroup":                  "---NONE---",
  "webFormAddress2":                   "/osdial/agent/webform_redirect.php",
  "allowTabSwitch":                    true,
  "answersPerHourLimit":               0,
  "previewForceDialTime":              10,
  "manualPreviewDefault":              true,
  "webFormExternalWindow":             false,
  "webForm2ExternalWindow":            false,
  "submitMethod":                      "NORMAL",
  "useCustom2CallierId":               false,
  "campaignLastCall":                  "",
  "useCidAreaCodeMap":                 false,
  "carrierId":                         7,
  "emailTemplate":                     "",
  "disableManualDial":                 false,
  "hideXferLocalCloser":               false,
  "hideXferDialOverride":              false,
  "hideXferHangupXfer":                false,
  "hideXferLeave3way":                 false,
  "hideXferDialWith":                  false,
  "hideXferHangupBoth":                false,
  "hideXferBlindXfer":                 false,
  "hideXferParkDial":                  false,
  "hideXferBlindVmail":                false,
  "allowMdHopperList":                 false,
  "ivrId":                             0
}

list =   {
"id"               : -1,
"name"             : "",
"campaignId"       : 0,
"active"           : true,
"description"      : "",
"scrubDNC"         : false,
"scrubInfo"        : "",
"cost"             : 0,
"webFormAddress"   : "",
"webFormAddress2"  : "",
"listScript"       : "",
"leadTransferId"   : "",
"changeDateTime"   : "", # 2019-08-29T16:06:02
}

lead =    {
    "id":                       -1,
    "entryDate":                "2019-09-03T00:00:00",
    "status":                   "NA",
    "user":                     "VDAD",
    "vendorLeadCode":           "",
    "sourceId":                 "",
    "listId":                   1381,
    "gmtOffsetNow":             0,
    "calledSinceLastReset":     "",
    "phoneCode":                "",
    "phoneNumber":              "",
    "title":                    "",
    "firstName":                "",
    "middleInitial":            "",
    "lastName":                 "",
    "address1":                 "",
    "address2":                 "",
    "address3":                 "",
    "city":                     "",
    "state":                    "",
    "province":                 "",
    "postalCode":               "",
    "countryCode":              "",
    "gender":                   "",
    "email":                    "",
    "custom1":                  "",
    "custom2":                  "",
    "cost":                     0,
    "organization":             "",
    "organizationTitle":        "",
    "statusExtended":           ""
  }